### ISSUE TITLE
not passing integer from flow to save to HerokuDB

### ISSUE THREAD

**Issue by tillo13** [manywho/service-sql#25]
andytillo [12:21 PM] 
Busy screenshot, but any ideas why Flow thinks the "probability" value is a string?  I realized I forgot to add it to the DBSave function: http://prntscr.com/hdxyjp  --I tried a v2 as `character_varying` in the db and Flow then doesn't recognize it as a number value, so I can't save it.  So I've just been trying (unsuccessfully) to save it as a different number type.  Thoughts on what I need to save it as?

**Comment by josecollazzi** [comment]
Hi @tillo13 , thank you for the report.

**Comment by josecollazzi** [comment]
@jonjomckay could you please review?

**Comment by josecollazzi** [comment]
@jonjomckay  could you please review the changes?

**Comment by jonjomckay** [comment]
@josecollazzi LGTM :+1:

**Comment by tillo13** [comment]
Tested this morning, and appears to be still throwing the same error --do I need to save the value in PostGresQL as something other than `integer`? http://prntscr.com/hfxvhk

**Comment by josecollazzi** [comment]
Hi @tillo13: 

The value 0.999.. it is not an integer, you should change the table schema to use nurmeric or decimal (https://www.postgresql.org/docs/9.1/static/datatype-numeric.html).

You weren't able to do it before because a bug in the service, but you should be able to use those types now on.

You don't need to update the service just the database schema.

**Comment by jonjomckay** [comment]
@josecollazzi we should probably catch any errors like that and give a friendlier message too :)

**Comment by tillo13** [comment]
That fixed it though!  Nice @josecollazzi!

**Comment by josecollazzi** [comment]
@jonjomckay  I agree, ticket created.
